config/routes.rb
Rails.application.routes.draw do
  get 'post/index'
  get 'post/dashboard'
  get 'post/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'post#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
   /validar los campos/ 
    validates :title, :url_link, :content, presence: true

    /Eliminar cierta parabra que no queramos/
    before_save :replace_word

    def replace_word
        self.content = self.content.gsub "spoiler", " "
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/post_controller.rb
class PostController < ApplicationController
 /http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: :dashboard/
  def index
    @posts = Post.all.order(created_at: :desc)

    if params[:title].present?
        @posts= Post.where('title = ?', params[:title])
      else
          @posts = Post.find_each
    end
  end

  def dashboard
  end

  def create
    @post = Post.create(title: params[:title], url_link: params[:url_link], content: params[:content])
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container" > 
    <!--Navbar para ingresar a las paginas--> 
    <nav class="navbar navbar-light bg-light">
      <form class="form-inline">
        <button class="btn btn-outline-success" type="button"><%= link_to 'POST', post_index_path  %></button>
        <button class="btn btn-outline-success" type="button"><%= link_to 'CREAR POST', post_dashboard_path  %></button>
      </form>
    </nav>
    <%= yield %>
  </body>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>

app/views/post/create.html.erb
<!-- @user es una variable = a todos los datos que pasamos al metodo, definida en el controlador pages-->
<% if @post.errors.any? %>
    <div id="error_explanation">
        <h2>
            <%= pluralize(@post.errors.count, "error") %>
            prohibited this user from being saved:
        </h2>

        <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% else %> <!--el else es para mostrar el mensaje de error o el registro con exito-->
    <h1> POST CREADO CON EXITO </h1>
<% end %>

app/views/post/dashboard.html.erb
<h1>Dashboard</h1>
<form method='get' action='/post/create' id="create_posts">

    <div class='form-group'>    
        <label for="title">Titulo:</label> 
        <input name="title" class="form-control" id="title" >
    </div>

    <div class='form-group'>    
        <label for="url_link">URL:</label> 
        <input name='url_link' class="form-control" placeholder="Enter URL">
    </div>

    <div class='form-group'>    
        <label for="content">Contenido:</label>  
        <textarea name='content' class="form-control" placeholder="Enter post"></textarea>
    </div>

    <div class='form-group'>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

app/views/post/index.html.erb
<nav class="navbar navbar-light bg-light justify-content-between">
    <a class="navbar-brand">My Blog </a>
        <form class="form-inline">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="title" >
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
</nav>
<br>
<table class="table">
    <thead>
        <tr>
            <th>TITULO</th>
            <th>URL</th>
            <th>CONTENIDO</th>
            <th>FECHA DE CREACION</th>
        </tr>
    </thead>
    <tbody>
        <% @posts.each do |post|%>
            <tr>
                <td><%= post.title %></td>
                <td><%= post.url_link %></td>
                <td><%= post.content %></td>
                <td><%= post.created_at %></td>
            </tr> 
        <% end %>
    </tbody>
</table>